[package]
name = "modman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
async-trait = "0.1.68"
clap = { version = "4.2.1", features = ["derive"] }
duplicate = "1.0.0"
ferinth = "2.7.4"
furse = "1.5.9"
futures-util = "0.3.28"
fuzzy-matcher = "0.3.7"
indicatif = "0.17.3"
inquire = "0.6.1"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
quickxml_to_serde = "0.5.0"
reqwest = { version = "0.11.16", features = ["stream", "json"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.7.3"
zip = "0.6.4"
