[package]
name = "modman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
ferinth = "2.7.4"
furse = "1.5.9"
futures-util = "0.3.28"
indicatif = "0.17.3"
reqwest = { version = "0.11.16", features = ["stream"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["full"] }
